name = "https-monitor"
main = "worker/index.mjs"
compatibility_date = "2026-07-17"

[[kv_namespaces]]
binding = "MONITOR_STATE"
id = "1904061dc67541cc9d73bafe58ad83e7"

[triggers]
crons = ["*/5 * * * *"]
